import { Geist, Geist_Mono } from "next/font/google";
import { Nunito } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/Navbar";
import Footer from "@/component/Footer";
import EnquiryForm from "@/component/EnquiryForm";
import Whatsapp from "@/component/Whatsapp";
import CallIcon from "@/component/CallIcon";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const nunito = Nunito({
  subsets: ['latin'],
  weight: ['200','300','400','500','600', '700'],
})
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Apna Chhota School",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${nunito.className} antialiased`}
      >
        <CallIcon />
        <Whatsapp />
        <Navbar />
        <EnquiryForm />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
